---
- hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
    vcenter_server: "10.15.50.57"
    vcenter_user: "root"
    vcenter_pass: "glglgl.123"
    #datacenter_name: "Datacenter"
    #cluster_name: "Test Cluster"
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: aacl002-onHost
      template: slce7-tmpl
      #datacenter: "{{ datacenter_name }}"
      folder: /datastore-toto-07/VM
      #cluster: "{{ cluster_name }}"
      datastore: "datastore-toto-07"
      networks:
      - name: VM Network
        ip: 10.15.50.88
        netmask: 255.0.0.0
        gateway: 10.15.50.1
        type: static
        dns_servers: 127.0.0.1
      customization:
        hostname: "aacl002_onHost"
        dns_servers:
        - 127.0.0.1
        - 1.1.1.1
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost
