---
- hosts: localhost
  gather_facts: no
  become: true
  become_user: root
  vars:
    #ansible_python_interpreter: /usr/bin/python3.6
    vcenter_server: "10.15.50.81"
    vcenter_user: "administrator@tpka.local"
    vcenter_pass: "Aglglgl.!23"
    datacenter_name: "Datacenter"
    #cluster_name: "Test Cluster"
  tasks:
  - name: Gather DNS facts about all ESXi Hosts in given Cluster
    vmware_host_dns_facts:
    #community.vmware.vmware_host_dns_info:
    #community.vmware.vmware_host_dns_facts:
      validate_certs: False
      hostname: '{{ vcenter_server }}'
      username: '{{ vcenter_user }}'
      password: '{{ vcenter_pass }}'
      cluster_name: "Test Cluster"
      register: dns_info
  - debug: msg="{{ dns_info.stdout }}"
      #esxi_hostname: "10.15.50.40"
    delegate_to: localhost